FROM mcr.microsoft.com/dotnet/core/sdk
LABEL author=”TobiasC”
ENV ASPNETCORE_URLS=http://+:5000 
ENV ASPNETCORE_ENVIRONMENT=”development”
EXPOSE 5000
WORKDIR /app 
COPY [“WebApplication1.csproj", “C:\Users\Bruger\source\repos\WebApplication1"]	//Copy source project
CMD [“/bin/bash”, “-c”, “dotnet restore && dotnet run”] //build and start program
