#stage 1
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
Label author="Tobias"
WORKDIR /app

#stage 2
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["WebApplication1/WebApplication1.csproj", "WebApplication1"]
RUN dotnet restore "WebApplication1/WebApplication1.csproj"
COPY